name: Mac Automation - Dependency Check and Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mac-automation:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Required Dependencies
        run: |
          echo "Checking required dependencies..."

          REQUIRED_TOOLS=("java" "node" "npm" "appium")

          for tool in "${REQUIRED_TOOLS[@]}"; do
            if ! command -v "$tool" &> /dev/null; then
              echo "Error: Missing dependency '$tool'. Please install it before running the pipeline."
              exit 1
            else
              echo "$tool found"
            fi
          done

          echo "All dependencies are installed."

      - name: Run Automation Tests
        run: |
          echo "Running automation tests..."
          java -jar Mac_runnable.jar | tee automation.log
