name: Paltalk Mac Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mac-automation:
    runs-on: self-hosted   # Mac runner you registered
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Paltalk bundle ID
        run: |
          echo "Checking bundle ID for Paltalk..."
          osascript -e 'id of app "Paltalk"'

      - name: Ensure Appium + mac2 driver installed
        run: |
          echo "Installing Appium + mac2 driver..."
          npm install -g appium@next
          appium driver install mac2 || true
          echo "Installed Appium drivers:"
          appium driver list --installed

      - name: Start Appium server in background
        run: |
          echo "Starting Appium server..."
          nohup appium --address 127.0.0.1 --port 4723 --log-level debug > appium.log 2>&1 &
          echo $! > appium.pid
          sleep 10
          echo "Appium started with PID: $(cat appium.pid)"

      - name: Tail Appium logs (background)
        run: |
          echo "Tailing Appium logs..."
          nohup tail -f appium.log > appium-tail.log 2>&1 &

      - name: Run automation JAR
        run: |
          echo "Running automation tests..."
          java -jar target/automation.jar | tee automation.log

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mac-automation-logs
          path: |
            appium.log
            appium-tail.log
            automation.log
