name: Mac Automation - Dependency Check and Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mac-automation:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Required Dependencies
        run: |
          echo "Checking required dependencies..."

          REQUIRED_TOOLS=("java" "node" "npm" "appium")

          for tool in "${REQUIRED_TOOLS[@]}"; do
            if ! command -v "$tool" &> /dev/null; then
              echo "Error: Missing dependency '$tool'. Please install it before running the pipeline."
              exit 1
            else
              echo "$tool found"
            fi
          done

          echo "All dependencies are installed."

      - name: Start Appium server
        run: |
          echo "Starting Appium server..."
          nohup appium --address 127.0.0.1 --port 4723 --log-level info > appium.log 2>&1 &
          echo $! > appium.pid
          sleep 10

          if curl -s http://127.0.0.1:4723/status | grep -q '"ready":true'; then
            echo "Appium started successfully."
          else
            echo "Error: Appium server failed to start."
            cat appium.log
            exit 1
          fi
          
      - name: Stop Appium server
        if: always()
        run: |
          if [ -f appium.pid ]; then
            echo "Stopping Appium server..."
            kill -9 $(cat appium.pid) || true
            rm -f appium.pid
            echo "Appium stopped."
          else
            echo "No Appium PID file found. Skipping stop step."
          fi

      - name: Run Automation Tests
        run: |
          echo "Running automation tests..."
          java -jar Mac_runnable.jar | tee automation.log
